### ISSUE TITLE
Will relite-js be deprecated?

### ISSUE THREAD

**Issue by anlexN** [seppo0010/rlite-js#1]

**Comment by seppo0010** [comment]
why do you ask?

**Comment by anlexN** [comment]
because you have long time to not update your code.
![image](https://user-images.githubusercontent.com/8686739/35478370-a0f5ef70-0416-11e8-83c9-024bb867c29c.png)

**Comment by seppo0010** [comment]
I'm not actively developing it, but if there's any bug or problem, I'll fix it.
